### ISSUE TITLE
specify read in data

### ISSUE THREAD

**Issue by cathalgking** [sgibb/MALDIquantExamples#2]
I use the import function to read data to a MassSpec S4 object taking data from a csv file. However, the S4 object does not seem to identify the correct intensity and m/z columns, as shown below. How can I specify the columns that should be used for these values?
<img width="721" alt="Screenshot 2024-01-16 at 9 33 36 pm" src="https://github.com/sgibb/MALDIquantExamples/assets/32261323/476a08e7-d1c0-48b4-b4bc-a58f3e09d00a">

**Comment by sgibb** [comment]
Unfortunately, there is no way to change the order of columns. The first column has to be *m/z* and the second *intensity*. You could switch the order of columns in `NEG_tumor_full_mini` before you call `write.csv`.
